stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  script:
    - echo "Running unit test"
run_lint_tests:
  stage: test
  script:
    - echo "Running lint test"

build_image:
  stage: build
  script:
    - echo "Running build image"

push_image:
  stage: build
  needs:
    - build_image
  script:
    - echo "Running push image"

deploy_image:
  stage: deploy
  script:
    - echo "Running deploy image"
