stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  before_script:
    - echo "(job keyword) Preparing test data..."
    - pwd
    - ls
    - mkdir test-data
    - ls
  script:
    - echo "Shell script that is executed by a runner..."
  after_script:
    - echo "(job keyword) Cleaning up temporary data..."
    - rm -r test-data
    - ls

run_lint_tests:
  stage: test
  script:
    - echo "Running lint test"

build_image:
  stage: build
  script:
    - echo "Running build image"
push_image:
  stage: build
  script:
    - echo "Running push image"

deploy_image:
  stage: deploy
  script:
    - echo "Running deploy image"
