# run only when the pipeline is triggered on the main branch or initiated by a merge request event. If it's triggered on any other branch and not related to a merge request, the pipeline won't execute
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH !="main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always
stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  script:
    - echo "Running unit test"
run_lint_tests:
  stage: test
  script:
    - echo "Running lint test"

build_image:
  stage: build
  script:
    - echo "Running build image"

push_image:
  stage: build
  needs:
    - build_image
  script:
    - echo "Running push image"

deploy_image:
  stage: deploy
  script:
    - echo "Running deploy image"
