# for all jobs in this pipeline will use node.js image
default:
  image: node:hydrogen-alpine3.20

variables:
  IMAGE_TAG: "v1.0"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH !="main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - test
  - build
  - deploy

run_unit_tests:
  variables:
    JOB_VAR: "Visible only in this job"
    ANOTHER_JOB_VAR: "Can define few job variables"
  stage: test
  script:
    - echo "Running unit test for project $PROJECT_NAME"
    - echo "job variable is $JOB_VAR"
    - echo "and next job variable is $ANOTHER_JOB_VAR"
    # check that node.js image is being used
    - npm version

run_lint_tests:
  # can specify image per job. This overrides the global defined image or default image
  image: ubuntu:20.04
  stage: test
  script:
    - echo "Running lint test for project $PROJECT_NAME"
    - echo "I can show global var $IMAGE_TAG but can't show $JOB_VAR"
    # check that Ubuntu image is being used
    - cat /etc/os-release

build_image:
  stage: build
  script:
    - echo "Running build image $IMAGE_NAME with next configuration - $PROPERTIES_FILE"
    - cat $PROPERTIES_FILE

push_image:
  stage: build
  needs:
    - build_image
  script:
    - echo "Running push image $IMAGE_NAME"

deploy_image:
  stage: deploy
  script:
    - echo "Running deploy image $IMAGE_NAME"
