---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - namespace.yaml  # Ensures the 'dev' namespace exists
buildMetadata:
  - managedByLabel
namespace: dev # Automatically assigns 'dev' to all rendered objects
