---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo
  name: todo
spec:
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - image: ghcr.io/username/todo:1.0
          imagePullPolicy: IfNotPresent
          name: todo
          ports:
            - containerPort: 3000
      # This security context will be removed according to the patch specified in ../overlay/kustomization.yaml under patches.patch
      securityContext:
        runAsGroup: 0
        runAsUser: 0
