vpc_cidr_block    = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avail_zone        = "eu-central-1a"
env_prefix        = "dev"
my_ip             = "0.0.0.0/0"
instance_type     = "t2.micro"
my_publick_key_location = "~/.ssh/aws.pub"
