---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - namespace.yaml
buildMetadata:
  - managedByLabel
namespace: dev
labels:
  - pairs:
      app.kubernetes.io/env: dev
# Specifies the container images to be used, including their tags
images: # define images to be used in the ../base/deployment.yaml
  - name: ghcr.io/username/todo
    newTag: dev
