apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
labels:
  - pairs:
      app.kubernetes.io/env: prod
buildMetadata:
  - managedByLabel
  - originAnnotations
resources:
  - ../../bases/todo
  - namespace.yaml
components: # List of components to include
  - ../../components/mysql
  - ../../components/security-context
  - ../../components/ingress
