---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator: # generating ConfigMaps
  - name: db # name of the ConfigMap to be created
    literals: # key-value pairs to be included in the ConfigMap
      - SQLITE_DB_LOCATION=/tmp/todos/todo.db
      # this configMap is used in a Deployment ./base/deployment.yaml
