apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo
spec:
  ingressClassName: nginx
  rules:
  - host: your_domain_name.com
    http:
      paths:
      - backend:
          service:
            name: todo
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
