apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo # Name of the Deployment to be patched
spec:
  template:
    spec:
      containers:
        - name: todo # Name of the container to be configured
          # Next three lines will be added to the Deployment container specification after applying the Kustomization
          envFrom:
            - configMapRef:
                name: db
